/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package professionalpractise;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.ImageIcon;

/**
 *
 * @author prathibha
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblExit = new javax.swing.JLabel();
        lblPlay = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 667));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/professionalpractise/images/EXIT-NORMAL.png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblExitMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
        });
        getContentPane().add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 250, 110));

        lblPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/professionalpractise/images/PLAY-NORMAL.png"))); // NOI18N
        lblPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblPlayMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblPlayMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPlayMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPlayMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPlayMouseEntered(evt);
            }
        });
        getContentPane().add(lblPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 250, 110));

        lblClose.setFont(new java.awt.Font("Avenir Next", 1, 36)); // NOI18N
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
        });
        getContentPane().add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 30, 40));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/professionalpractise/images/background1-P.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 667));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        // TODO add your handling code here:
        lblClose.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lblCloseMousePressed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        lblClose.setForeground(Color.LIGHT_GRAY);
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        // TODO add your handling code here:
        setCursor(Cursor.DEFAULT_CURSOR);
        lblClose.setForeground(Color.black);
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        // TODO add your handling code here:
        setCursor(Cursor.HAND_CURSOR);
        lblClose.setForeground(Color.white);
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblPlayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlayMousePressed
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/professionalpractise/images/PLAY-PRESSED.png"));
        lblPlay.setIcon(II);
    }//GEN-LAST:event_lblPlayMousePressed

    private void lblPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlayMouseClicked
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/professionalpractise/images/PLAY-PRESSED.png"));

        lblPlay.setIcon(II);
        this.dispose();
        Memo memo=new Memo();
        memo.setVisible(true);
    }//GEN-LAST:event_lblPlayMouseClicked

    private void lblPlayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlayMouseExited
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/professionalpractise/images/PLAY-NORMAL.png"));
        lblPlay.setIcon(II);
    }//GEN-LAST:event_lblPlayMouseExited

    private void lblPlayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlayMouseEntered
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/professionalpractise/images/PLAY-ENTER.png"));
        lblPlay.setIcon(II);
    }//GEN-LAST:event_lblPlayMouseEntered

    private void lblPlayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlayMouseReleased
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/professionalpractise/images/PLAY-ENTER.png"));
        lblPlay.setIcon(II);
        
    }//GEN-LAST:event_lblPlayMouseReleased

    private void lblExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMousePressed
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/professionalpractise/images/EXIT-PRESSED.png"));
        lblExit.setIcon(II);
    }//GEN-LAST:event_lblExitMousePressed

    private void lblExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseReleased
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/professionalpractise/images/EXIT-ENTER.png"));
        lblExit.setIcon(II);
    }//GEN-LAST:event_lblExitMouseReleased

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/professionalpractise/images/EXIT-PRESSED.png"));
        lblExit.setIcon(II);
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/professionalpractise/images/EXIT-NORMAL.png"));
        lblExit.setIcon(II);
    }//GEN-LAST:event_lblExitMouseExited

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/professionalpractise/images/EXIT-ENTER.png"));
        lblExit.setIcon(II);
    }//GEN-LAST:event_lblExitMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblPlay;
    // End of variables declaration//GEN-END:variables
}
