/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package professionalpractise;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.Timer;
import static professionalpractise.Memo.Q5;

/**
 *
 * @author prathibha
 */
public class Memo1 extends javax.swing.JFrame {

    /**
     * Creates new form Memo
     */
    
    public static String Q1 = Memo.Q1;
    public static String Q2 = Memo.Q2;
    public static String Q3 = Memo.Q3;
    public static String Q4 = Memo.Q4;
    public static String Q5 = Memo.Q5;
    
   
    String s1= "<html>&nbsp;&nbsp;How old are you?</html>";
    String s2= "<html>&nbsp;&nbsp;What is your birth month?</html>";
    String s3= "<html>&nbsp;&nbsp;What is your birth day?</html>";
    String s4= "<html>&nbsp;&nbsp;What is your favourite number?(0-99)</html>";
    String s5= "<html>&nbsp;&nbsp;How many members are there <br> &nbsp;&nbsp;in your family?</html>";
    
    int counter = 0;
    
    public Memo1() {
        initComponents();
        ImageIcon i2 = new ImageIcon(getClass().getResource("/professionalpractise/images/background7-P.png"));
        lblNext.setVisible(false);
        HideLabelonly(lblNext, 4100, true);
        HideLabel(lblLComplete, 4000, "<html>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Are you ready?<br>Please click NEXT button</html>");
        lblBackground.setIcon(i2);
        txtAnswer.setVisible(false);
        lblisRemember.setText("");
        
        HideLabel(jLabel1, 1000, "33");
        HideLabel(jLabel1, 2000, "");
        
    }
    
    public void HideLabel(JLabel label,int Time,String string){
        Timer t = new Timer(Time, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                label.setText(string);
            }
        });
        t.setRepeats(false);
        t.start();
        
    }
    
    public void HideLabelonly(JLabel label,int Time,boolean x){
        Timer t = new Timer(Time, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                label.setVisible(x);
            }
        });
        t.setRepeats(false);
        t.start();
        
    }
    
    public void HideTextFiled(JTextField txt,int Time,String string){
        Timer t = new Timer(Time, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                txt.setText(string);
            }
        });
        t.setRepeats(false);
        t.start();
        
    }
    
    public void change(){
       counter ++;
       
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblisRemember = new javax.swing.JLabel();
        lblShowNumbertoM = new javax.swing.JLabel();
        lblLComplete = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNext = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        txtAnswer = new javax.swing.JTextField();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 667));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 667));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblisRemember.setFont(new java.awt.Font("Luckiest Guy", 0, 36)); // NOI18N
        lblisRemember.setForeground(new java.awt.Color(255, 255, 255));
        lblisRemember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblisRemember.setText("<html>ARE YOU <br>REMEMBER...?</html>");
        getContentPane().add(lblisRemember, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 230, 110));

        lblShowNumbertoM.setFont(new java.awt.Font("Luckiest Guy", 0, 80)); // NOI18N
        lblShowNumbertoM.setForeground(new java.awt.Color(255, 255, 255));
        lblShowNumbertoM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblShowNumbertoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 650, 140));

        lblLComplete.setFont(new java.awt.Font("BadaBoom BB", 0, 40)); // NOI18N
        lblLComplete.setForeground(new java.awt.Color(255, 255, 255));
        lblLComplete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLComplete.setText("<html>Ok.. Now i’ll show you<br> some number patters..<br> try to remember those..</html>");
        getContentPane().add(lblLComplete, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 410, 170));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 220, -1));

        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/professionalpractise/images/NEXT-NORMAL.png"))); // NOI18N
        lblNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblNextMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblNextMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNextMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNextMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNextMouseEntered(evt);
            }
        });
        getContentPane().add(lblNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, 180, 80));

        lblClose.setFont(new java.awt.Font("Avenir Next", 1, 36)); // NOI18N
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
        });
        getContentPane().add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 30, 40));

        txtAnswer.setBackground(new java.awt.Color(235, 235, 235));
        txtAnswer.setFont(new java.awt.Font("Luckiest Guy", 1, 45)); // NOI18N
        txtAnswer.setForeground(new java.awt.Color(47, 47, 47));
        txtAnswer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAnswer.setBorder(null);
        txtAnswer.setSelectionColor(new java.awt.Color(0, 204, 255));
        txtAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnswerActionPerformed(evt);
            }
        });
        getContentPane().add(txtAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 390, 80));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/professionalpractise/images/background9-P.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 667));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnswerActionPerformed

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        // TODO add your handling code here:
        lblClose.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lblCloseMousePressed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        lblClose.setForeground(Color.LIGHT_GRAY);
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        // TODO add your handling code here:
        setCursor(Cursor.DEFAULT_CURSOR);
        lblClose.setForeground(Color.black);
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        // TODO add your handling code here:
        setCursor(Cursor.HAND_CURSOR);
        lblClose.setForeground(Color.white);
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblNextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMousePressed
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/professionalpractise/images/NEXT-PRESSED.png"));
        lblNext.setIcon(II);
    }//GEN-LAST:event_lblNextMousePressed

    private void lblNextMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseReleased
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/professionalpractise/images/NEXT-ENTER.png"));
        lblNext.setIcon(II);

    }//GEN-LAST:event_lblNextMouseReleased

    private void lblNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseClicked
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/professionalpractise/images/NEXT-PRESSED.png"));

        lblNext.setIcon(II);
        
        
        System.out.println("c" +counter);
        //
        //txtAnswer.setText("");
        if(counter==0){
            lblLComplete.setVisible(false);
            ImageIcon i2=new ImageIcon(getClass().getResource("/professionalpractise/images/background8-P.png"));
            lblBackground.setIcon(i2);
            lblShowNumbertoM.setVisible(true);
            HideLabel(lblShowNumbertoM, 1000, ""+Q1+Q2+Q3);
            HideLabel(lblShowNumbertoM, 3000, "<html><font size= 25>Please click next</html>");
            
        }
        else if(counter==1){
            lblisRemember.setText("<html>ARE YOU <br>REMEMBER...?</html>");
            lblShowNumbertoM.setVisible(false);
            txtAnswer.setVisible(true);
            ImageIcon i2=new ImageIcon(getClass().getResource("/professionalpractise/images/background9-P.png"));
            lblBackground.setIcon(i2);
            txtAnswer.requestFocus();
            
        }
        else if(!(txtAnswer == null)){
            if((Q1+Q2+Q3).equals(txtAnswer.getText())){
                System.exit(0);
            }
            else{
                ImageIcon i2=new ImageIcon(getClass().getResource("/professionalpractise/images/background1-P.png"));
                lblBackground.setIcon(i2);
            }
        }
        
        
        
       
        change();
        txtAnswer.setText("");
        System.out.println("Q1-"+Q1);
        System.out.println("Q2-"+Q2);
        System.out.println("Q3-"+Q3);
        System.out.println("Q3-"+Q4);
        System.out.println("Q3-"+Q5);
        
        
    }//GEN-LAST:event_lblNextMouseClicked

    private void lblNextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseExited
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/professionalpractise/images/NEXT-NORMAL.png"));
        lblNext.setIcon(II);
    }//GEN-LAST:event_lblNextMouseExited

    private void lblNextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseEntered
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/professionalpractise/images/NEXT-ENTER.png"));
        lblNext.setIcon(II);
    }//GEN-LAST:event_lblNextMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Memo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Memo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Memo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Memo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Memo1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblLComplete;
    private javax.swing.JLabel lblNext;
    private javax.swing.JLabel lblShowNumbertoM;
    private javax.swing.JLabel lblisRemember;
    private javax.swing.JTextField txtAnswer;
    // End of variables declaration//GEN-END:variables
}
